name: earstoworld

services:
  backend:
    image: suh021/earstoworld:latest
    container_name: backend
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_DB_USERNAME: ${MYSQL_DB_USERNAME}
      MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    networks:
      - ktb_network
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${DIST_DIR}/dist:/usr/share/nginx/html  # React 빌드 결과를 Nginx에 연결
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ktb_network
    restart: always

networks:
  ktb_network:
    driver: bridge
